### PR TITLE
Add SnapshotExtension for spock-specs (#1620

### PR DESCRIPTION
**Pull request by leonard84**
This is a very limited implementation of the snapshotting pattern
with special focus on the needs of Spock.
So, it is not a public extension.

### CODE REVIEW

**Comment by Vampire** [comment]
I didn't look at the changes, but if it is not to be used publicly but only for testing Spock, why then not implementing it in `src/test`?

**Comment by leonard84** [comment]
Mainly to indicate that it is infrastructure code and not really part of the any test itself, the other ad-hoc extensions in `src/test` are mostly for testing features in one way or the other.

**Comment by Vampire** [comment]
> Mainly to indicate that it is infrastructure code and not really part of the any test itself, the other ad-hoc extensions in `src/test` are mostly for testing features in one way or the other.

But it is more part of the test code, than the production code if it is only to be used by tests of Spock itself.
If you want a clearer separation, maybe use `java-test-fixtures` plugin and put the infrastructure code there?

**Comment by Vampire** [comment]
Argh, ignore me. It is in `spock-specs`, so it's fine of course, stupid me.

**Pull request merged**
