### PR TITLE
Recognize Marcin E. in release notes for 2.0-M5

### PR DESCRIPTION
**Pull request by szpak**
Related to support for injection into @Shared fields in spock-spring:
https://github.com/spockframework/spock/pull/1255

### CODE REVIEW

**Review by leonard84 — APPROVED** [review]

**Comment by leonard84** [comment]
Thanks, I was going to do that later, I merged his change after I updated the notes and forgot to add it in the conflict resolution.

**Comment by szpak** [comment]
I see. During your today presentation at the Gr8Conf Friday, I've noticed that he is missing and I thought that you miss that writing the release notes for that (long awaited) feature :).

**Comment by erdi** [comment]
Thanks for going as far as submitting a PR for this, @szpak! That's appreciated.

**Comment by szpak** [comment]
So long awaited feature you implemented. I couldn't resist :)

**Pull request merged**
