### PR TITLE
Detached mocks (Issue 305)

### PR DESCRIPTION
**Pull request by leonard84**
Implemented Spock Issue 305 according to https://groups.google.com/forum/#!topic/spockframework/pZXrWKzRV5U

### CODE REVIEW

**Comment by aaronzirbes** [comment]
cc: @pniederw we're running into this issue with some of our Spring Boot projects.  Any possibility of getting this merged?

**Comment by pniederw** [comment]
The feature is desirable, but it would have to be implemented differently (as discussed on the mailing list).

**Comment by aaronzirbes** [comment]
Thanks Peter, I'll go check out the thread.  In the mean time we ended up using Mockito to instantiate the beans we needed to mock out.

**Comment by leonard84** [comment]
@pniederw could we define what needs to be done and what the requirements are exactly so we can get it into Spock at last.

* common API for mock creation that contains all factory methods currently found in `spock.lang.MockingApi`
 * the implementation of that MockingApi in `java.lang.Specification` would automatically attach mocks to the current spec instance
 * standalone implementation whose mocks would need to be manually attached to a spec instance
 * automatically attachment from mocks defined in a spring context with `SpringMockTestExecutionListener`
* extending the MockingApi to allow spying on existing instances using
 * a proxy approach
 * a prototype approach


Open questions:
* Currently `spock.lang.MockingApi` extends `org.spockframework.lang.SpecInternals`, I think if we want to have a standalone version then we need to extract it as an interface or restructure them since there are some methods that don't belong in the mocking api e.g., `interaction` or the `thrownImpl` and `checkExceptionThrown` methods.
* Which spy method should we use?

**Comment by pniederw** [comment]
Sounds good. Yes, an interface will have to be extracted. If `MockingApi` contains methods (e.g. `interaction`) that aren't meaningful for mock *creation*, a `MockFactory` interface could be extracted instead. I don't understand the spy related question.

**Comment by leonard84** [comment]
@pniederw regarding the spy topic: we discussed it already on the mailing list (https://groups.google.com/forum/#!topic/spockframework/pZXrWKzRV5U) and this was your last reply
>It feels like a huge hack. Then again, it seems to do well in Mockito.

I counted it as an agreement to the proposed extension of the spy capabilities, i.e., being able to construct spies around existing instances.

Regarding the `MockFactory`, I would also exclude the no-argument methods `Mock()`, `Stub()`, `Spy()` since it will not be possible to determine the type of the requested mock based on the type of the target variable.

**Comment by pniederw** [comment]
> I counted it as an agreement to the proposed extension of the spy capabilities, i.e., being able to construct spies around existing instances.

Let's keep this separate from this pull request.

> Regarding the MockFactory, I would also exclude the no-argument methods Mock(), Stub(), Spy()

Alternatively, one could have a unified MockFactory interface, and throw an `UnsupportedOperationException` for the (few) methods which cannot be supported by the standalone implementation.

**Comment by leonard84** [comment]
While extracting the `MockFactory` interface and implementing the `StandaloneMockFactory` I noticed some other problems. The factory methods in `SpecInternals` all have a inferredName parameter which is unavailable in the standalone case. So we either use a fixed name based on the type or something, or require the use of the `options` map with a `name` option.

Should the initialization `Closure` be supported and if so, how should it behave? Should it be stored in the mock and executed each time it is attached to a spec? If we are not supporting them, we should throw `UnsupportedOperationException` instead of simply ignoring them.

How should the classloader be passed? It is normally taken from the spec but in the detached case I added it as parameter instead of the spec.

**Comment by rehevkor5** [comment]
Is there some kind of workaround for this?

**Comment by leonard84** [comment]
I will open a new PR this rebase makes no sense to review.

**Pull request closed without merging**
