### PR TITLE
Solve the problem of Spock application in integration test

### PR DESCRIPTION
**Pull request by zhangfanghui8**
In the spring Dubbo project, solve the problem that the member variables of the Java class containing the annotation @Reference cannot be mocked

---
This change is [Reviewable](https://reviewable.io/reviews/spockframework/spock/1141)

### CODE REVIEW

**Comment by Vampire** [comment]
This is not a full review, just two points. Please translate the code comments to English. And you miss documentation for your new module.

**Comment by szpak** [comment]
@zhangfanghui8 Thanks for your proposal.

First of all, I don't have experience with Dubbo and I cannot verify its correctness, especially that there is no integration tests confirming it works at all.

While Spock has some additional modules for things like Unitils or Tapestry those modules are rather in the maintainance mode as not necessary people usually contributing to Spock uses it on a daily basis. This makes it harder to keep up-to-date with the development of the upstream projects and it seems that Dubbo is in rapid development. Looking at the code I have doubts (see bellow) if this code has been "widely used in production" which makes me even more reluctant to have that module in Spock.

My proposal is to create a separate project (it's even not a Spock extension, but could be mentioned [here](https://github.com/spockframework/spock/wiki/Third-Party-Extensions)) to stabilize code, improve testing, get feedback from other people/projects and see how it works.

Some random remarks after a brief look at the code:
 - possible compatibility concerns:
> final String  reference = "com.alibaba.dubbo.config.annotation.Reference";

seems to be [deprecated](https://github.com/apache/dubbo/blob/master/dubbo-common/src/main/java/com/alibaba/dubbo/config/annotation/Reference.java) in favor of [org.apache....](https://github.com/apache/dubbo/blob/master/dubbo-common/src/main/java/org/apache/dubbo/config/annotation/Reference.java)

 - The implementation with the fields traversal and injection seems somehow hacky. I haven't tested it and don't know the details, but I would expect to have `@Reference` to be treated by Spring as a regular field to inject (something similar to [this implementation](https://www.baeldung.com/spring-annotation-bean-pre-processor)). Then for Spock it would be transparent - Spock in general replaces/wraps beans in the Spring context with mocks and takes care about their initialization and cleaning up. The is no looking for `@Autowired`, `@Inject`, `@Repository`, etc. in `spock-spring`. You might want to take a look how the postprocessor in spring-dubbo handles that - maybe it could be done in more generic way (e.g. similar problem could be with Mockito and Spring Boot).

 - as the code deals only with Spring probably spock-spring-dubo would be a better name

 - as @Vampire already mentioned comments in English, documentation how to us it, proper code formatting and testing would be beneficial for your projects in a standalone form.

**Comment by zhangfanghui8** [comment]
> This is not a full review, just two points. Please translate the code comments to English. And you miss documentation for your new module.

👌

**Comment by zhangfanghui8** [comment]
> @zhangfanghui8 Thanks for your proposal.
> 
> First of all, I don't have experience with Dubbo and I cannot verify its correctness, especially that there is no integration tests confirming it works at all.
> 
> While Spock has some additional modules for things like Unitils or Tapestry those modules are rather in the maintainance mode as not necessary people usually contributing to Spock uses it on a daily basis. This makes it harder to keep up-to-date with the development of the upstream projects and it seems that Dubbo is in rapid development. Looking at the code I have doubts (see bellow) if this code has been "widely used in production" which makes me even more reluctant to have that module in Spock.
> 
> My proposal is to create a separate project (it's even not a Spock extension, but could be mentioned [here](https://github.com/spockframework/spock/wiki/Third-Party-Extensions)) to stabilize code, improve testing, get feedback from other people/projects and see how it works.
> 
> Some random remarks after a brief look at the code:
> 
> * possible compatibility concerns:
> 
> > final String  reference = "com.alibaba.dubbo.config.annotation.Reference";
> 
> seems to be [deprecated](https://github.com/apache/dubbo/blob/master/dubbo-common/src/main/java/com/alibaba/dubbo/config/annotation/Reference.java) in favor of [org.apache....](https://github.com/apache/dubbo/blob/master/dubbo-common/src/main/java/org/apache/dubbo/config/annotation/Reference.java)
> 
> * The implementation with the fields traversal and injection seems somehow hacky. I haven't tested it and don't know the details, but I would expect to have `@Reference` to be treated by Spring as a regular field to inject (something similar to [this implementation](https://www.baeldung.com/spring-annotation-bean-pre-processor)). Then for Spock it would be transparent - Spock in general replaces/wraps beans in the Spring context with mocks and takes care about their initialization and cleaning up. The is no looking for `@Autowired`, `@Inject`, `@Repository`, etc. in `spock-spring`. You might want to take a look how the postprocessor in spring-dubbo handles that - maybe it could be done in more generic way (e.g. similar problem could be with Mockito and Spring Boot).
> * as the code deals only with Spring probably spock-spring-dubo would be a better name
> * as @Vampire already mentioned comments in English, documentation how to us it, proper code formatting and testing would be beneficial for your projects in a standalone form.



> @ zhangfanghui8感谢您的建议。
> 
> 首先，我没有使用Dubbo的经验，也无法验证其正确性，尤其是没有集成测试可证明其完全可以工作。
> 
> 尽管Spock拥有一些其他模块来处理诸如Unitils或Tapestry之类的问题，但这些模块仍处于维护模式，因为通常不需要为Spock做出贡献的人们每天都在使用它。这样就很难跟上上游项目的最新动态，而且Dubbo似乎正在快速发展。查看代码，我对此代码是否已“广泛用于生产环境”感到怀疑（请参见下面的信息），这使我更加不愿意在Spock中使用该模块。
> 
> 我的建议是创建一个单独的项目（甚至不是Spock扩展，但可以在[此处](https://github.com/spockframework/spock/wiki/Third-Party-Extensions)提及）来稳定代码，改进测试，从其他人/项目获得反馈并查看其工作方式。
> 
> 简要看一下代码后的一些随机评论：
> 
> * 可能的兼容性问题：
> 
> > 最终字符串参考=“ com.alibaba.dubbo.config.annotation.Reference”;
> 
> 似乎是[过时](https://github.com/apache/dubbo/blob/master/dubbo-common/src/main/java/com/alibaba/dubbo/config/annotation/Reference.java)赞成[org.apache ....](https://github.com/apache/dubbo/blob/master/dubbo-common/src/main/java/org/apache/dubbo/config/annotation/Reference.java)
> 
> * 使用字段遍历和注入的实现似乎有点黑。我还没有测试它，也不知道细节，但是我希望`@Reference`Spring 必须将其视为要注入的常规字段（类似于[此实现](https://www.baeldung.com/spring-annotation-bean-pre-processor)）。然后对于Spock来说将是透明的-Spock通常在Spring上下文中用模拟替换/包装bean，并注意它们的初始化和清理。在没有寻找`@Autowired`，`@Inject`，`@Repository`等，`spock-spring`。您可能想看看spring-dubbo中的后处理器如何处理-也许可以用更通用的方式来完成（例如，类似的问题可能是Mockito和Spring Boot）。
> * 因为该代码仅涉及Spring，所以spock-spring-dubo可能是一个更好的名称
> * 正如@Vampire提到的英文注释，如何使用它的文档，正确的代码格式和测试将以独立的形式对您的项目有利。

At present, it is only used in our company, because there is just a need for integration testing

> @ zhangfanghui8感谢您的建议。
> 
> 首先，我没有使用Dubbo的经验，也无法验证其正确性，尤其是没有集成测试可证明其完全可以工作。
> 
> 尽管Spock拥有一些其他模块来处理诸如Unitils或Tapestry之类的问题，但这些模块仍处于维护模式，因为通常不需要为Spock做出贡献的人们每天都在使用它。这样就很难跟上上游项目的最新动态，而且Dubbo似乎正在快速发展。查看代码，我对此代码是否已“广泛用于生产环境”感到怀疑（请参见下面的信息），这使我更加不愿意在Spock中使用该模块。
> 
> 我的建议是创建一个单独的项目（甚至不是Spock扩展，但可以在[此处](https://github.com/spockframework/spock/wiki/Third-Party-Extensions)提及）来稳定代码，改进测试，从其他人/项目获得反馈并查看其工作方式。
> 
> 简要看一下代码后的一些随机评论：
> 
> * 可能的兼容性问题：
> 
> > 最终字符串参考=“ com.alibaba.dubbo.config.annotation.Reference”;
> 
> 似乎是[过时](https://github.com/apache/dubbo/blob/master/dubbo-common/src/main/java/com/alibaba/dubbo/config/annotation/Reference.java)赞成[org.apache ....](https://github.com/apache/dubbo/blob/master/dubbo-common/src/main/java/org/apache/dubbo/config/annotation/Reference.java)
> 
> * 使用字段遍历和注入的实现似乎有点黑。我还没有测试它，也不知道细节，但是我希望`@Reference`Spring 必须将其视为要注入的常规字段（类似于[此实现](https://www.baeldung.com/spring-annotation-bean-pre-processor)）。然后对于Spock来说将是透明的-Spock通常在Spring上下文中用模拟替换/包装bean，并注意它们的初始化和清理。在没有寻找`@Autowired`，`@Inject`，`@Repository`等，`spock-spring`。您可能想看看spring-dubbo中的后处理器如何处理-也许可以用更通用的方式来完成（例如，类似的问题可能是Mockito和Spring Boot）。
> * 因为该代码仅涉及Spring，所以spock-spring-dubo可能是一个更好的名称
> * 正如@Vampire提到的英文注释，如何使用它的文档，正确的代码格式和测试将以独立的形式对您的项目有利。
At present, it is only used in our company, because our company has the requirement of integration test.

I've made some adjustments. You can have a look. As for what you said, it's up to you to come up with a separate project.

**Comment by zhangfanghui8** [comment]
> @zhangfanghui8 Thanks for your proposal.
> 
> First of all, I don't have experience with Dubbo and I cannot verify its correctness, especially that there is no integration tests confirming it works at all.
> 
> While Spock has some additional modules for things like Unitils or Tapestry those modules are rather in the maintainance mode as not necessary people usually contributing to Spock uses it on a daily basis. This makes it harder to keep up-to-date with the development of the upstream projects and it seems that Dubbo is in rapid development. Looking at the code I have doubts (see bellow) if this code has been "widely used in production" which makes me even more reluctant to have that module in Spock.
> 
> My proposal is to create a separate project (it's even not a Spock extension, but could be mentioned [here](https://github.com/spockframework/spock/wiki/Third-Party-Extensions)) to stabilize code, improve testing, get feedback from other people/projects and see how it works.
> 
> Some random remarks after a brief look at the code:
> 
> * possible compatibility concerns:
> 
> > final String  reference = "com.alibaba.dubbo.config.annotation.Reference";
> 
> seems to be [deprecated](https://github.com/apache/dubbo/blob/master/dubbo-common/src/main/java/com/alibaba/dubbo/config/annotation/Reference.java) in favor of [org.apache....](https://github.com/apache/dubbo/blob/master/dubbo-common/src/main/java/org/apache/dubbo/config/annotation/Reference.java)
> 
> * The implementation with the fields traversal and injection seems somehow hacky. I haven't tested it and don't know the details, but I would expect to have `@Reference` to be treated by Spring as a regular field to inject (something similar to [this implementation](https://www.baeldung.com/spring-annotation-bean-pre-processor)). Then for Spock it would be transparent - Spock in general replaces/wraps beans in the Spring context with mocks and takes care about their initialization and cleaning up. The is no looking for `@Autowired`, `@Inject`, `@Repository`, etc. in `spock-spring`. You might want to take a look how the postprocessor in spring-dubbo handles that - maybe it could be done in more generic way (e.g. similar problem could be with Mockito and Spring Boot).
> * as the code deals only with Spring probably spock-spring-dubo would be a better name
> * as @Vampire already mentioned comments in English, documentation how to us it, proper code formatting and testing would be beneficial for your projects in a standalone form.

At present, it is only used in our company, because our company has the requirement of integration test.

I've made some adjustments to your suggestion. You can have a look. As for the possibility of independent projects, my answer is yes. It depends on you

**Comment by szpak** [comment]
> As for the possibility of independent projects, my answer is yes. It depends on you

I would definitely go that way to get feedback and stabilize the codebase. Feel free to mention the project here once released to Maven Central (and add it [here](https://github.com/spockframework/spock/wiki/Third-Party-Extensions)).

IMO having integration tests - even in your own project - is a MUST to know that the new version actually works (manual testing has some disadvantages ;-) ).

In addition I would follow the suggestion to get know how Spring in production knows about injecting something into the `@Reference` field (probably some bean post-processor similar to [that](https://www.baeldung.com/spring-annotation-bean-pre-processor)) and maybe it would make the code required to have it work with Spock easier to write :).

**Comment by leonard84** [comment]
Hi @zhangfanghui8 first of all thank you for your PR, but unfortunately I'll have to decline adding it to the spock main codebase. @szpak already explained the reasons. I'd suggest to release it as a standalone extension then we can list it here https://github.com/spockframework/spock/wiki/Third-Party-Extensions

**Comment by zhangfanghui8** [comment]
@szpak  ok，thanks

**Comment by zhangfanghui8** [comment]
@leonard84 ok

**Pull request closed without merging**
