### PR TITLE
Added spockAndroidJar Task

### PR DESCRIPTION
**Pull request by AndrewReitz**
This task creates a jar file that has java.beans package
replaced with the grooid (groovy for android) jar's
version of java.beans

Relates to #60

---
This change is [Reviewable](https://reviewable.io/reviews/spockframework/spock/66)

### CODE REVIEW

**Comment by pieces029** [comment]
I realized this doesn't get added to the task dependency chain, I'll add that in.'

Also, this does not get included with the publishing jars. I will try to get that figured out but some advisement would be helpful.

**Comment by robfletcher** [comment]
Is the new jar required for on-device testing?

**Comment by pieces029** [comment]
@robfletcher Sorry I haven't checked in on this until now. Yes, it would be helpful for on device testing, but is not required. It would allow for automatic getters and setters of java classes to be mocked.

As of right now if I have a `getValue` method, for example, I could not mock and provide interactions for it by writing something like `value.value >> 1`.

Here is everything that currently does work. https://github.com/pieces029/android-spock/blob/master/spock-android/src/androidTest/groovy/com/andrewreitz/spock/android/MockingSpec.groovy

I am actually thinking that I could include spock in that library with jarjar and achieve this same result.

On another note, what would you think about adding the [android-spock](https://github.com/pieces029/android-spock) library to the spock orginization on github?

**Comment by AndrewReitz** [comment]
I realized that was a long winded answer 😄 

The short answer is yes, this is a jar that would allow on device spock tests to run.

**Comment by leonard84** [comment]
There hasn't been any additional show of support for this, so I'm going to close it as unplanned.

**Pull request closed without merging**
