### PR TITLE
Duplicates occurring when generating unrolled causes test failures #1098

### PR DESCRIPTION
**Pull request by pbielicki**
This change is [Reviewable](https://reviewable.io/reviews/spockframework/spock/1099)

### CODE REVIEW

**Comment by marcphilipp** [comment]
How about appending the iteration count in brackets instead (like `SafeIterationNameProvider` does) in case a duplicate name is detected? That way the feature wouldn't have to be opt-in.

**Comment by Vampire** [comment]
I wouldn't enforce that, a user might like it that iterations are named the same. For example the navigation in IJ then works properly.

**Comment by pbielicki** [comment]
@marcphilipp that is another valid option, but I'd like this to be a conscious decision of the user, thus hidden behind a (possibly yet another) flag

**Comment by marcphilipp** [comment]
> For example the navigation in IJ then works properly.

Does it when using a pattern?

**Comment by Vampire** [comment]
When using a pattern other than `#featureName`, the iterations are not named the same most probably. But if that is the pattern or there is actually no pattern used, the iterations are named all like the feature and navigation works. And with my fancy naming PR, you could rely on the the default naming to have the data variables in the name and if you want to have better IDE navigation temporarily, you can set a system variable to the pattern of `#featureName` and all iterations are named like the feature.

**Comment by leonard84** [comment]
What are we trying to solve here?

1. You don't notice duplicated names, but you probably don't have a problem. Not ideal, but you probably won't go searching for the flag for a problem you don't even know about.
2.  If you already noticed non-unique names, then you could just fix them. 

So if we hide it behind a flag, it would probably only be used by you. However, if we don't do that, then we add the performance penalty to everyone.  And I bet that at best only very few people are affected by this issue.

This could also be done with as a third-party extension, so instead of setting the flag you'd add the extension. I'm personally leaning to this solution.

At the end of the day, it is probably an issue with the reporting tool, at least for Spock 2.x, since it will report a `UniqueId` in addition to the displayed name.

**Pull request closed without merging**
