### PR TITLE
Support property getter stubbing without it (#1040)

### LINKED ISSUE #1040: Stubbing a property getter only works with "it."
Having this:

```java
Guild server = Stub {
    it.roles >> [higherRole, lowerRole]
    getRoleById(higherRoleId) >> higherRole
}
```

works properly.
But removing the `it.` complains that the test class has no `roles` property.
So currently it works without qualifier for explicit methods, but not for property getters in property syntax.

### PR DESCRIPTION
**Pull request by Vampire**
Fixes #1040

---
This change is [Reviewable](https://reviewable.io/reviews/spockframework/spock/1121)

### CODE REVIEW

**Comment by leonard84** [comment]
Can the same approach be used to for methods as well? Currently we have an ugly workaround with an identity closure.

**Comment by Vampire** [comment]
I don't think so for the work-around you are talking about.

Here we are handling interactions.
What I do here is, I check whether there is a variable expression that is referencing a non-existing variable within the supported closures with implicit parameter.
If it is one, I handle it like it were a property expression `it.foo` where `foo` is the variable name.
The point here is, if we have the case I check for, then the target must be the delegate of the closure and never the owner or thisObject, so we don't need to follow any delegation strategy, it must always be the mock the closure is called for due to `with` or mock creation.

The work-around you are talking about is totally different.
It is about rewriting implicit conditions where the expression needs to follow the delegation strategy as it could also refer to one of the owners up the caion or the thisObject, so we cannot use `it` or `delegate` here without changing the logic.
Such an implicit method or property condition is a `PropertyExpression` or `MethodCallExpression` on implicit `this`, which in the context of a closure means it follows the delegation strategy, in that case "closure itself -> delegate -> owner".

If it is a `MethodCallExpression`, it is rewritten to something like
```
SpockRuntime.verifyMethodCondition(
    $spock_errorCollector, // errorCollector
    $spock_valueRecorder.reset(), // recorder
    'containsKey(\'value2\')', // text
    14, // line
    7, // column
    null, // message
    this, // target
    $spock_valueRecorder.record($spock_valueRecorder.startRecordingValue(0), 'containsKey'), // method
    new java.lang.Object[], // args
    $spock_valueRecorder.realizeNas(4, false), // safe
    false, // explicit
    3 // lastVariableNum
)
```

The important part here is that `target` and `method` are given in separate arguments.
The target is taken from the orginal `MethodCallExpression`.
The problem is, that the target of the original `MethodCallExpression` is the `VariableExpression` `this` and the `MethodCallExpression` is the one knowing that it is an implicit `this`.

So you need to give the closure as target to `verifyMethodCondition` to get the desired behavior.
And the only way I too see to get hold of the closure is to either use a `PropertyExpression` or `MethodCallExpression` with implicit `this` that returns the actual closure.
I'm not aware of any property that could be abused for that.
So only some `MethodCallExpression` can be used.

Alternatively to the current
```groovy
    return new MethodCallExpression(
      new VariableExpression("this"),
      new ConstantExpression("each"),
      new ArgumentListExpression(
        new PropertyExpression(
          new ClassExpression(ClassHelper.makeWithoutCaching(Closure.class)),
          new ConstantExpression("IDENTITY")
        )
      )
    );
```
we could use one of
```groovy
    return new MethodCallExpression(
      new VariableExpression("this"),
      new ConstantExpression("tap"),
      new ArgumentListExpression(
        new PropertyExpression(
          new ClassExpression(ClassHelper.makeWithoutCaching(Closure.class)),
          new ConstantExpression("IDENTITY")
        )
      )
    );
```
or
```groovy
    return new MethodCallExpression(
      new VariableExpression("this"),
      new ConstantExpression("find"),
      NO_ARGUMENTS
    );
```
or
```groovy
    return new MethodCallExpression(
      new VariableExpression("this"),
      new ConstantExpression("asType"),
      new ArgumentListExpression(
        new ClassExpression(ClassHelper.makeWithoutCaching(Closure.class))
      )
    );
```
Where the identity closure in the current code and in my `tap` code is absolutely irrelevant.
We could instead also use any other arbitrary side-effect-free closure that does not fail or create a new empty closure.
It is exeucted against the closure we call it on, but its result is not considered at all.

**Comment by szpak** [comment]
@Vampire be aware that force-push cancels previous merge approvals :).

**Comment by Vampire** [comment]
Yeah, I know, I just can't adapt to the in **my** opinion horrible practice to always use squash merges.
I usually rebase my PRs until they get merged finally and if I split something in multiple commits, I want those to survive.
Maybe sometime I learn that I should do differently for Spock.
I just tried to make Travis build the PR properly.
Your merge from master was also not successfully built.

**Comment by szpak** [comment]
Having Travis red should block merge (or squash).

image

**Comment by Vampire** [comment]
Yes, it became green after my rebase. Previously you pressed the "Update Branch" button and it still remained red due to some unknown problem.

**Comment by szpak** [comment]
Some code is hard to cover Codecov:
image

**Comment by szpak** [comment]
Regarding squashing for complex PRs I also like to have more than one commit which makes it easier to read (and understand) later or, or revert partially.

**Pull request merged**
