### PR TITLE
Started adding basic instructions into the docs.

### PR DESCRIPTION
**Pull request by gregopet**
Hi,

I admired the new Spock documentation but it lacks the basic info that is often needed when one isn't quite a Spock ninja yet :)

I took a shot at adding the basics: mostly this stuff is copied from the Google Code basic tutorial with a bit of editing. I also added a paragraph and a very simple code sample right at the beginning to make it easier for newcomers to follow the text. In fact all of the edits were meant to make the text more approachable.

If you think I'm on a good track I can complete the rest of the sections and of course I would be glad to accept any suggestions and/or objections.

### CODE REVIEW

**Comment by robfletcher** [comment]
Any reason this was done on the `groovy-1.8` branch rather than `master`?

**Comment by gregopet** [comment]
No particular reason (at least that I remember - I submitted this over a year ago). Probably just a mistake on my part :(

**Comment by gregopet** [comment]
If you find my submit useful, is there anything I can do (e.g. create another pull request on the master branch)?

**Comment by leonard84** [comment]
I think this PR is obsolete as it was already included in the spock_primer https://spockframework.github.io/spock/docs/1.0/spock_primer.html or did I miss something?

**Comment by gregopet** [comment]
Nope, you didn't miss anything - either I wasn't aware of Spock primer when I created this pull request or it didn't even (publicly) exist back then, yet. Closing pull request.

**Pull request closed without merging**
