### PR TITLE
Block asserts

### PR DESCRIPTION
**Pull request by Fuud**
Added new method `Specification.verifyAll(Closure)`. All conditions in provided closure will be evaluated and reported as MultipleFailureException. If an exception occures in non-condition statement, all previously captured exceptions will be reported.

Example:
```
public class Test extends Specification {
    def "test1"() {
        expect:
            verifyAll{
              1 == 2
              3 == 4
            }
    }
}
```
Will report two failures.

As #50 it is based on exceptions-in-conditions-as-condition-failure ( #549 for this PR and #49 for #50)

### CODE REVIEW

**Comment by szpak** [comment]
Duplicate of (long merge awaiting) #50.

**Comment by Fuud** [comment]
Sorry. Wrong commits was pushed. I will repush it tomorrow.

**Comment by robfletcher** [comment]
It looks like this PR conflicts with the changes merged from #549

**Comment by robfletcher** [comment]
Merged in #595

**Pull request closed without merging**
