### PR TITLE
Fix compile error for nested conditions without top-level condition (#1232)

### LINKED ISSUE #1232: Nested asserts cannot be transformed
Hey,

We've just tried out latest `Spock 2.0-M4`, we're getting the following exception:
> Task :compileTestGroovy
startup failed:
NestedAssertTest.groovy: -1: The current scope already contains a variable of the name $spock_errorCollector
 @ line -1, column -1.
NestedAssertTest.groovy: -1: The current scope already contains a variable of the name $spock_valueRecorder
 @ line -1, column -1.
2 errors

The cause seems to be that nested` assert`s seem to generate conflicting code, irrespective of their level or other previously generated ones (can be `"".with {}` or whatever closure):
```groovy
def nestedAssert() {
    tap {
        assert 0
        tap { assert 0 }
    }
}
```

The following reproducer can be used by running `./gradlew build`:
https://github.com/paplorinc/spock-bug/blob/master/src/test/groovy/NestedAssertTest.groovy

### PR DESCRIPTION
**Pull request by leonard84**
fixes #1232

@Vampire maybe you have a better solution, I did a bisect and the commit b0507d9e6a16d78f3dcd9b037237ce76c46c8c3f introduced the error.

### CODE REVIEW

**Comment by Vampire** [comment]
Hm, it happens during the `VariableScopeVisitor`.
I'm wondering whether this is another bug of it we hit or if we do something wrongly.

And what I wonder even more is, I played around without your PR and the example rtretyak (not OP) posted in the issue.
If I try with that example it complains about double declaration of the two variables.
But if I replace in `org.spockframework.compiler.SpecRewriter#defineRecorders`
`new VariableExpression(SpockNames.VALUE_RECORDER, nodeCache.ValueRecorder),` by
`new VariableExpression(SpockNames.VALUE_RECORDER + i++, nodeCache.ValueRecorder),`
and
`new VariableExpression(SpockNames.ERROR_COLLECTOR, nodeCache.ErrorCollector),` by
`new VariableExpression(SpockNames.ERROR_COLLECTOR + i++, nodeCache.ErrorCollector),`,
having in the same class a `private static int i = 1;`
there is no double declaration anymore of course as they have unique names.

But if you look at the result of the symantic analysis phase in the AST Browser of the Groovy console, then there is only one of each variables, not two. So I wonder why how and where are the inner ones removed again that the `VariableScopeVisitor` complains about.

**Comment by leonard84** [comment]
If I understand your experiment correctly, I think they are removed since nothing is referencing those names, unless you change the code that is referencing those variables as well.

**Comment by Vampire** [comment]
Neither the inner nor the outer ones are used, so why are the inner removed, but the outer not?

**Comment by Vampire** [comment]
Ah, forget what I said, the inner ones are still there, I just again fell into the trap of the AST browser rendering arrays without content but only as `new Object[]`. *grml*

But actually I wondered what the difference now is between the `groupConditionFound` and the `anyConditionFound`.
And wondered whether a `verifyAll {}` somewhere in that closures hierarchy would also break it.

And interestingly it does not, but produces `$spock_errorCollector`, and in the next nesting `$spock_errorCollector1` and then `$spock_errorCollector2` and so on.
So maybe the better fix would be within the `RecorderScopeNameRewriter` and finding out why it does not rename the one that fails the compilation?

**Comment by Vampire** [comment]
Ah, the `RecorderScopeNameRewriter` per-se is working fine, if it is actually invoked.

This compiles and works perfectly fine:
```
import spock.lang.*

class Test extends Specification {
  def test1() {
    expect:
    assert 1 // 1
    with([1,2]) {
      it.size() > 0
      it.each { assert it > 0 }
    }
  }

  def tes2t() {
    expect:
    tap {
      assert 1
      tap { assert 1 }
    }
  }
  
  def test3() {
    assert 0 // 2
    tap {
      assert 0
      tap { assert 0 }
    }
  }
}
```
But if you remove either line marked with 1 or 2 it fails with the error message.
While fixing #783, you invoked the `RecorderScopeNameRewriter` only if `methodHasCondition` is `true`.
`methodHasCondition` is only `true` if you have a condition or group condition (`verifyAll`) on top level.
By removing line marked with 1 or 2 this condition is not satisfied, but the first-level `tap` and second-level `tap` or `with` and `each` both define the two variables as both contain conditions.
`test2` works, because `tap` returns a value and thus counts as condition whereas in `test1` the `with` returns `void` and thus is no implicit condition.

So if you simply move the `RecorderScopeNameRewriter` invocation out of the `if`, the issue is fixed.
If you think this is would hit performance too much, then I would at least suggest to not change when `methodHasCondition` is `true`, but move the `RecorderScopeNameRewriter` into its own `if` that checks for `anyConditionFound`, because now you define useless additional two variables and a useless try-finally-validateCollectedErrors construct.

And additionally I think you should make clear in the test that there must not be a top-level assertion and also add a test for a feature method like shown and then of course adapt the PR title / commit message.



Btw. while reading this code and investigating, I think we currently produce much unnecessary code that makes the execution slower than necessary. The error collector only collects errors and throws on `validateCollectedErrors()` if it was given `true` as argument which only happens if you are within a group condition. Otherwise the error collector immediately throws an exception immediately. And as we know whether group condition is true or not generating the try/finally block and the validate call is totally superfluous and probably unnecessary in 95% of the cases as I don't think many users us `verifyAll`.

**Comment by Vampire** [comment]
And if you want to keep the `anyCondition` maybe rename it to `deepCondition` or something like that.
It is hard to grasp just from the name what the difference between `condition`, `groupCondition` and `anyCondition` is.
Just from the names I'd guess `anyCondition = condition || groupCondition` :-)

**Comment by Vampire** [comment]
Or actually you could call `RecorderScopeNameRewriter` only if `defineRecorders` was called multiple times, because even if it was called only one time it is unnecessary to iterate the whole code again to fixup those names.

**Comment by Vampire** [comment]
Or actually maybe the best idea would be to throw away the `RecorderScopeNameRewriter` alltogether and instead simply generate the variables and calls with unique names right away.
Because currently we generate bad code just to then iterate over it and fix it when we probably could right away generate good code.
I think I'd like that solution the most.

**Comment by leonard84** [comment]
@Vampire would you like to improve this PR? AST transforms are still not my forte.

**Comment by Vampire** [comment]
I actually started to give it a shot last night, trying the last suggestion.
But then it was not that "simple" as the value recorder is used in many places and that means you have to pass around the current index to those places.
To fix it right away is no rocket science but mainly tedious suffix forwarding and I grew tired and sleepy.
So the question actually still is, do we want to produce "bad" code and then fix it with the separate tree-walk or do we want to generate good code right away and pass around the suffixes.
I'm not sure I have time for the latter right now, but you could certainly do it :-D

**Comment by leonard84** [comment]
> But then it was not that "simple" as the value recorder is used in many places and that means you have to pass around the current index to those places.

Yes, that was the reason I went with the `RecorderScopeNameRewriter`, not the best solution but it did fix the problem and didn't require extensive changing of existing AST code. I still find the AST *Rewriter code confusing, how everything ties into each other and passing an index around seemed troublesome, since you also have to decrement it again, if you exit the closure and so on.

**Comment by Vampire** [comment]
After looking at it with a fresh mind, it wasn't that hard actually.
I replaced your commit.
So let's swap rules, please do a review, even if you cannot approve as it is your own PR. :-)

**Review by leonard84 — COMMENTED** [review]
LGTM

**Review by Vampire — APPROVED** [review]
lgtl

**Pull request merged**
