### PR TITLE
support later groovy versions including 3.0+

### PR DESCRIPTION
**Pull request by paulk-asert**
Hi, a PR for supporting later versions of Groovy. We are currently wanting to move Groovy master to 3.0.0 but have held back since we currently use some Spock tests in some of the modules.

Locally when testing this I changed the baseVersion to 1.2 but didn't include that in the PR as I am not sure what your plans are in that regard. Perhaps it is time for a 1.1 branch and this could go on a master branch along with things like PR#632?

At the moment there aren't any breaking changes in master that we are aware of, so I didn't make another variant. (There is possibly a change in 2.4.10 which impacts Spock but that is another issue - run the Spock build using 2.4.10 and see test failures if you want details).

We are however about to merge a bunch of largish features into later branches, so we'll need to track what happens as we go. As long as you are only releasing SNAPSHOTs in the 1.2 stream and Groovy is only doing SNAPSHOTs too, I think all should be good.

### CODE REVIEW

**Comment by leonard84** [comment]
@paulk-asert thanks for your PR, allowing spock-2.4 to run with groovy 3.x might be problematic if you guys decide to break binary compatibility later in development. However if you would be ok with snapshot versions of spock then I think it would be fine to add something like `maxGroovyVersion = snapshotVersion ? "3.9.99" : "2.9.99"` what do you think?

Do you have a hint what changed in groovy 2.4.10 that causes the additional exception in verifyAll? From a cursory look at http://groovy-lang.org/changelogs/changelog-2.4.10.html I didn't see anything obvious?

And while we are at it, we'd like to drop support for older Java Versions, would groovy (3.0) be fine with Java 8?

**Comment by paulk-asert** [comment]
Hi, we won't want a snapshot version bundled in any zip or mentioned in any pom once we release a non-snapshot version ourselves but it is fine while we do our testing. We'll hopefully know in a few weeks whether any binary breaking change has occurred once we have all the main features we know about merged. And we'll just have to monitor after that until we cut an alpha release in case any further changes are made. I might add Spock to our CI server as a nightly joint build.

Wrt the 2.4.10 change. I haven't investigated properly yet but I'd guess one of these:
[GROOVY-8085] - Exception in "finally" not caught by outer "try" (probably)
[GROOVY-7248] - MissingPropertyException: No such property in finally block (not likely but only other one that seems related to the problem)

The problem is in VerifyAllSpecification#verifyAll as you noticed. As well as picking up the two expected errors. It gets a third which is a org.junit.runners.model.MultipleFailureException containing the other two. I'd guess that there are two levels of try somewhere in Spock and prior to GROOVY-8085, Groovy wasn't correctly processing both levels. Now that it is, an extra exception is being added to the failure list. I'll investigate further and provide another PR if I get time but I have some higher priority items on my todo list for the next week or so.

Wrt to Java 8. Current master branch of Groovy will be Java 8+ only. This will either be Groovy 3.0 or 4.0 depending on some other features we are still trying to bed down with a back-ported JDK7-compatible version of the new Parrot parser. Currently the backport is destined for Groovy 2.6 and master for 3.0 but if any breaking changes are noticed in the backport, it will become 3.0 (still on JDK7) and master will become 4.0 (on JDK8).

**Comment by paulk-asert** [comment]
Actually, to support testing from our end, would it be possible to allow the groovyVersion to be set manually. Some sort of hasProperty check? We'd test spock against our latest 2.4, 2.5 etc. snapshots.

**Comment by leonard84** [comment]
@paulk-asert what do you mean exactly, would you like to overwrite the min/maxVersion in the check or just disable the version check altogether? Here are the relevant code locations `org.spockframework.util.SpockReleaseInfo#isCompatibleGroovyVersion` and `org.spockframework.util.VersionChecker#checkGroovyVersion`.

I think we could add something like `if (Boolean.getBoolean("spock.disableGroovyVersionCheck")) return true;` to `isCompatibleGroovyVersion`.

**Comment by paulk-asert** [comment]
Instead of building with 2.4.6 or 2.4.9 or whatever you have in your build file as the groovyVersion, I want to build with 2.4.11-SNAPSHOT for instance. That would find things like the 2.4.7 and 2.4.10 changes much earlier. I'll create another PR.

**Comment by leonard84** [comment]
Ok, then could you change this PR to only include the fix for the `ConfigurationScriptLoader`.

**Comment by paulk-asert** [comment]
PR changed - let me know if that was what you were after for this PR

**Pull request merged**
