### PR TITLE
Fix pending feature logic

### PR DESCRIPTION
**Pull request by Vampire**
Again, only last commit to look at for now, rest is just other PRs combined for less conflicts. :-)

---
This change is [Reviewable](https://reviewable.io/reviews/spockframework/spock/1103)

### CODE REVIEW

**Comment by szpak** [comment]
@leonard84 After #1101 is merged, that one has "just" one commit. Do you have any remarks about the code?

**Comment by leonard84** [comment]
@Vampire I see no tests that have been fixed by this commit, or new tests that verify the changed behavior.

**Comment by Vampire** [comment]
Why not? I'm pretty sure the tests in `PendingFeatureExtensionSpec` will fail if you revert the changes in the other classes, except I made some stupid refactoring error again.

**Comment by leonard84** [comment]
Sorry, I was fooled by the Review UI, the last file was collapsed because it was too large and so I overlooked it.

**Comment by Vampire** [comment]
Yep, no refactoring error this time: `26 tests completed, 11 failed`

**Pull request merged**
