### PR TITLE
Fix regression with multi-assignment of method call result

### LINKED ISSUE #1332: 2.0 final - regression with `thrown` block
# Issue description
This worked in `2.0-M5-groovy-3.0` but broke in `2.0-groovy-3.0`.

# How to reproduce
```groovy
package test

import spock.lang.Specification

class SomeSpec extends Specification {
	def 'bar'() {
		when:
		def (a, b) = foo()

		then:
		thrown(Exception)
	}
}
```

The problem is with the deconstruction of the result of `foo()`. With it the Spock compiler blows up:

```
Description	Resource	Path	Location	Type
Groovy:Unexpected error during compilation of spec 'test.SomeSpec'. Maybe you have used invalid Spock syntax? Anyway, please file a bug report at http://issues.spockframework.org.
```

# Additional Environment information
Eclipse IDE. Same result with Gradle.

## Java/JDK
```
openjdk 15.0.2 2021-01-19
OpenJDK Runtime Environment (build 15.0.2+7)
OpenJDK 64-Bit Server VM (build 15.0.2+7, mixed mode)
```

## Groovy version
3.0.7

## Build tool version
`2.0-groovy-3.0`

### Gradle
`Gradle 7.0.2`

## Operating System
Linux

## IDE
Eclipse

### PR DESCRIPTION
**Pull request by leonard84**
caused by #1314

fixes #1332

### CODE REVIEW

**Review by Vampire — DISMISSED** [review]
Lgtm, except for the massive amount of unrelated whitespace changes.
This makes review very hard and also seeing the real change later when browsing the history.
Could you consider reverting all the unrelated whitespace changes and maybe reformat the whole codebase with the settings you want to have within an own commit?

**Comment by leonard84** [comment]
Yeah didn't notice the whitespace change, I really need to make the reformat commit for the whole codebase.

**Comment by kriegaex** [comment]
> Lgtm, except for the massive amount of unrelated whitespace changes.

Maybe this helps, if something like this happens again unintentionally:
image

**Comment by iNikem** [comment]
@leonard84 Any estimations when this fix will be released?

**Pull request merged**
