### PR TITLE
Check instance field access in data variable assignments

### PR DESCRIPTION
**Pull request by Vampire**

### CODE REVIEW

**Comment by leonard84** [comment]
While this is not wrong per se, it does prevent an advanced use-case where you `rehydrate` the closure before you use it.

**Comment by Vampire** [comment]
The same is already done for data pipes and the user guide states explicitly that from a where block only shared and static fields may be accessed. This PR just adds the missing check in data variable assignments.

**Comment by leonard84** [comment]
> and the user guide states explicitly that from a where block only shared and static fields may be accessed

Granted, but WDYT of allowing it for closures and performing an implicit `rehydrate` for closure parameters instead, when passing them to the method?
This won't work for the case you've shown here as the closures are directly called, but maybe that could be handled too.

**Comment by Vampire** [comment]
I'm not sure we do ourselves a favor if we do so.
The code could theoretically be arbitrary complex and figuring out the semantics of whether the closure is called within the data provider method or during the test might be non-trivial.

What could be done instead if someone is bored, is replacing the references inside lambdas that are currently complained about by some wrapper or method like the shared field accesses that verifies at runtime whether it is being used during data provider execution or during the actual test run, so the error would come as runtime error instead of compiler error.
But this PR is just for adding the currently missing check, the more common case is that those references are used outside a closure.
The other tactic would be an improvement that could be done separately.
And it could also involve an automatic rehydrate of closures where the `owner`, `delegate` and `thisObject` are set to the iteration instance if they are set to the shared instance (each individually)

Besides that, if you really need it, you can easily work-around the compiler check by using a helper method that accesses the instance field for you.
But then you of course have to also rehydrate the closure or is accesses the shared instance.
So this will work even with this PR:
```groovy
def instanceField
def getIt() { instanceField }
def foo() {
  instanceField = 666
  x = x.rehydrate(this, this, this)

  expect:
  x() == 666

  where:
  x = { getIt() }
}
```

**Review by leonard84 — APPROVED** [review]

**Pull request merged**
