### PR TITLE
Add documentation for @NotYetImplemented to extension docu (Issue #84)

### PR DESCRIPTION
**Pull request by leonard84**

### CODE REVIEW

**Comment by leonard84** [comment]
@pniederw failing build has nothing to do with the change, for some reason the cglib depdendency in one variation is pulled from jitpack and not from maven central. This jar seems to be borked and causes NoClassDefFoundErrors
> Download https://jitpack.io/com/github/cglib/cglib.cglib-nodep/e10bc3dda2/cglib.cglib-nodep-e10bc3dda2.jar
https://travis-ci.org/spockframework/spock/jobs/61651812

**Comment by jitpack-io** [comment]
If the error is on our side we'll work on resolving the issue.

**Comment by leonard84** [comment]
@jitpack-io I've looked a bit more into it, and it seems that the `jarjar-maven-plugin` is not being executed and thus the asm dependencies are not shaded into the jar.

**Comment by szpak** [comment]
@leonard84 It can be probably closed as currently pending features seem to be covered in the project [documentation](https://github.com/spockframework/spock/blob/master/docs/extensions.adoc#pendingfeature).

**Comment by robfletcher** [comment]
@szpak is correct `@PendingFeature` covers this.

**Pull request closed without merging**
