### PR TITLE
Spock 2.0 fix skipped test count

### PR DESCRIPTION
**Pull request by tburny**
The `SpockHelloWorldTest` failed because each `FeatureNode` was of type `CONTAINER` and had an `IterationNode` as child. Appearently when a `CONTAINER` node is skipped, it does not generate any test event that show up in the summary of the unit test.

There are two cases:
* A `SimpleFeatureNode` represents the test itself. It should not have any children, thus it is of type `TEST` (a _leaf_ node in the tree). It delegates to an `IterationNode` without having it as a child.
* A `ParametrizedFeatureNode` represents both a container and (probably) a test itself. It can have zero or more `IteratioNode`s and the test results in all children summarize the test itself. This it should be either of type `CONTAINER` or `CONTAINER_AND_TEST`.

Additionally I added the possiblity to skip a whole `SpecNode` altogehter (`@Ignore(If)` on the specification class).

---
This change is [Reviewable](https://reviewable.io/reviews/spockframework/spock/981)

### CODE REVIEW

**Comment by leonard84** [comment]
@tburny there was a reason, for having SimpleFeature the way it is. Spock offers extension points on Feature and Iteration level, see http://spockframework.org/spock/docs/1.3/all_in_one.html#_interceptors. You would need to implement all before, after, and so on for the delegate in the execute method of the feature.

**Comment by tburny** [comment]
Oh now I understand. 
I assume that when a feature is marked as `skipped`, the iteration interceptor should not be executed, correct?

How about changing `FeatureNode.getType()` to
```java
  @Override
  public Type getType() {
    return featureInfo.isSkipped() ? Type.TEST : Type.CONTAINER;
  }
```
and pruning all its `IterationNode` children?

**Comment by leonard84** [comment]
@tburny the delegate way is more correct, the current problem is that the iteration node will also be reported. I was going to fix that later, but since you already started you might want to take care of it. The important thing is that the interceptors are still applied when using the delegate.

**Comment by tburny** [comment]
I think this should be better now. I rearranged the methods to match the interceptor lifecycle at http://spockframework.org/spock/docs/1.3/all_in_one.html#_interceptors and also added calls `super` so common event processing can be added in `FeatureNode`.

Open points:
1. There are quite a few places where a sensible reason phrase for `SkipResult.skipped(message)` could be provided. We can either use `SkipResult` in `SpecElementInfo` directly (instead of the `skipped` flag`) or wrap the `SkipResult` into a `SkipInfo` object to decouple the spock core from the JUnit Platform API. What do you think?
2. The JUnit Jupiter engine prunes all non-containers from the tree via `.addTestDescriptorVisitor(context -> TestDescriptor::prune)`. shall we do the same for the `SpockEngine`?

**Comment by leonard84** [comment]
@tburny thanks for your contribution.

**Pull request merged**
