### PR TITLE
Spock logo

### PR DESCRIPTION
**Pull request by sbglasius**
This is a proposal for a Spock Framework Logo.

Feel free to use it.

---
This change is [Reviewable](https://reviewable.io/reviews/spockframework/spock/34)

### CODE REVIEW

**Comment by andyvdh** [comment]
Sorry for duplicating an issue again (you can close #545)
What is the status on the logo design. Has a decision been taken already?

**Comment by Vad1mo** [comment]
It seems not to be that important.

**Comment by Vad1mo** [comment]
here is the [PSD](https://www.dropbox.com/s/eh8szk9gqaze92l/spock_logo.psd.zip?dl=1) fiel I used to play around with the logos.

**Comment by andyvdh** [comment]
@Vad1mo sorry to hear that. I really liked your logo designs. Especially the color usage. 
I also liked @leonard84's beaker idea, but this somehow reminds me of the [Puppet Labs](https://upload.wikimedia.org/wikipedia/en/c/c5/Puppet_Labs_Logo.png) logo

But we can use the red-green-refactor idea:

spock

**Comment by leonard84** [comment]
Its not that its not important, but none of the logos really convinced me. I think when we pick a logo its not just for the sake of having a logo, but having something cool and iconic.

I'm tending to agree with @sbglasius that we should raise money for a professionally designed logo.
* http://99designs.com/logo-design
* http://www.logosauce.com/
* http://www.crowdstudio.in/

The main question is how we should raise this money, there needs to be someone who actually handles the communication with the site/designers and pays them. Then we need a good way to raise the money, I don't think that kickstarter would be the best platform, maybe patreon but thats seems to be aimed at recurring donations.

**Comment by almibe** [comment]
To me this actually seems like a project that would work well being funding with kickstarter as long as you know the amount of money it would cost to fund a graphic designer beforehand.

From the kickstarter faq
```
A project is a finite work with a clear goal that you’d like to bring to life. Think albums, books, or films.
```
It's less ambitious than an book or a film but it is a finite work with a clear goal.  No matter what I'd like to throw a little bit of money at this.  For better or worse things like logos are important for championing/marketing open source projects.
Just my $0.02

**Comment by leonard84** [comment]
@almibe the reason I think that Kickstarter is not the best plattform for this is the time limit, and I don't know who would create a good pitch.

**Comment by Vad1mo** [comment]
Lets do the MVP Approach.

1. How much do we need or how much do we want to spend?
2. How many of you would chip in for a Spock Logo? 
3. How much would you chip in?

If we have enough people here, why should we look somewhere else?  

I am in with **30$**

**Comment by sbglasius** [comment]
@Vad1mo Can I suggest that you do a Google Form poll instead. Github comments is not the place to collect such information. But please publish the link here, and on social media.

**Comment by sbglasius** [comment]
@robfletcher @leonard84 @alkemist I would like to bring this up again. What is the status of an official spock logo?

**Comment by janisz** [comment]
Ping

**Comment by tburny** [comment]
Any news on this?

**Comment by leonard84** [comment]
Not really, finding a suitable way to collect the money is not easy.
There are things like crowdfunding campaign sites like Kickstarter, Indigogo.
Then there are ongoing support sites e.g., Patreon or OpenCollective.

All of these require work, the campaign most of all since it will have a fixed deadline and needs attention.
Then if we are lucky and overshoot the goal, what should happen with the excess money?

Then we would need to choose provider and manage the logo design campaign, that is also work.
* https://www.designcrowd.de/
* https://99designs.de/
* https://www.logosauce.com/
* http://www.crowdstudio.in/

IMHO, having no logo is better than having a bad logo and currently I don't have the time to work on those problems.

**Comment by postapczuk** [comment]
maybe sth like this? I just want show you the idea - Spock as a tenor drum hited with drumstick and casting out bugs ;)
spock svg

**Comment by leonard84** [comment]
@postapczuk thanks for your suggestion, but I see several issues.

1. The Image has to much detail, it will not look look to good if it is downsized
2. It lacks a good Iconic representation
3. I don't see any real connection between a drum being played and Spock

**Comment by postapczuk** [comment]
Ad. 1 - I'm not a graphic designer - just wanted to show you the idea with spock drum

Ad. 2 - see Ad. 1

Ad. 3 - so if the "spock" name is not connected with Spock from Star Trek and not with (via wiki) "accent drum used with tenor drums" so what the source of the name is?

**Comment by leonard84** [comment]
Ad 3. Spock is the amalgamation of **Sp**ecification and M**ock**, the association with Star Trek is intended but it should not be an obvious reference in the logo (trademark and other reasons).

As for the rest, I'm just pointing out why that logo is not acceptable, I'm not criticising you.

**Comment by szpak** [comment]
Just playing a necromancer to unearth a topic of the official logo of Spock Framework, in the context of 2.0.

Unfortunately, I'm not a designer, an artist or a painter and I cannot provide my own proposal for a logo.

**Comment by leonard84** [comment]
I sat down with a designer, but unfortunately she doesn't have the time to create a real logo from the scribbles.

Here are the three favorites:
SpockLogo

Here are all the scribbles:
[Spock_Logo_Scribbles_2.zip](https://github.com/spockframework/spock/files/4205980/Spock_Logo_Scribbles_2.zip)

**Comment by MaciejBart** [comment]
SPOCK5

**Comment by sbglasius** [comment]
@maciejBart that is actually a very good suggestion. IMO the best yet!

**Comment by goeh** [comment]
Maybe it's just me but I think it looks a little "aggressive". Maybe a dark green color (as in test should be green) would make it less aggressive. Keep the text black.

**Comment by janisz** [comment]
How about red and green like tests failing and passing. 
@MaciejBart can you prepare couple of different colour versions?

**Comment by MaciejBart** [comment]
Requested color versions
SPOCK9

**Comment by goeh** [comment]
Thanks @MaciejBart Here is a combination for reference
Spock-green-red

**Comment by leonard84** [comment]
Thanks for all the suggestions, the official logo has been decided.

**Comment by sbglasius** [comment]
Awesome. Where and when will it be available?

**Comment by janisz** [comment]
image

**Comment by leonard84** [comment]
@sbglasius see https://github.com/spockframework/spock-logo

**Pull request closed without merging**
