### PR TITLE
Add JDK 11 to Travis

### PR DESCRIPTION
**Pull request by MartyIX**
Unfortunately, the build fails because of: https://issues.apache.org/jira/browse/GROOVY-8727

---
This change is [Reviewable](https://reviewable.io/reviews/spockframework/spock/900)

### CODE REVIEW

**Comment by leonard84** [comment]
You need to enable Java 11 in the javaVersions in build.gradle

**Comment by MartyIX** [comment]
Ah, thanks

**Comment by MartyIX** [comment]
Those 

```
java.lang.IllegalAccessError: Update to static final field spock.util.concurrent.PollingConditionsSpec.$const$0 attempted from a different method (__$swapInit) than the initializer method <clinit>
            at spock.util.concurrent.PollingConditionsSpec.__$swapInit(PollingConditionsSpec.groovy)
            at spock.util.concurrent.PollingConditionsSpec.<clinit>(PollingConditionsSpec.groovy)
```

errors are quite interesting. The problem is in 

```
  private void createSpecInstance(boolean shared) {
    if (runStatus != OK) return;

    try {
      if (shared) {
        sharedInstance = (Specification) spec.getReflection().newInstance();  // <<<<<<<<<<< THIS LINE
        currentInstance = sharedInstance;
      } else {
        currentInstance = (Specification) spec.getReflection().newInstance();  // <<<<<<<<<<< THIS LINE
      }
    } catch (Throwable t) {
      throw new InternalSpockError("Failed to instantiate spec '%s'", t).withArgs(spec.getName());
    }

    getSpecificationContext().setCurrentSpec(spec);
    getSpecificationContext().setSharedInstance(sharedInstance);
  }
```

Stacktrace is: 

```
org.spockframework.util.StringMessagePrintStreamSpec > initializationError FAILED
    org.spockframework.util.InternalSpockError: Failed to instantiate spec 'StringMessagePrintStreamSpec'; 

java.lang.IllegalAccessError: Update to static final field org.spockframework.util.StringMessagePrintStreamSpec.$const$0 attempted from a different method (__$swapInit) than the initializer method <clinit> 
        at org.spockframework.util.StringMessagePrintStreamSpec.__$swapInit(StringMessagePrintStreamSpec.groovy)
        at org.spockframework.util.StringMessagePrintStreamSpec.<clinit>(StringMessagePrintStreamSpec.groovy)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.lang.Class.newInstance(Class.java:584)
        at org.spockframework.runtime.BaseSpecRunner.createSpecInstance(BaseSpecRunner.java:107)
        at org.spockframework.runtime.BaseSpecRunner.run(BaseSpecRunner.java:65)
        at org.spockframework.runtime.Sputnik.run(Sputnik.java:63)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
        at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:117)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:834)


```

**Comment by leonard84** [comment]
No, worries I was testing https://reviewable.io/reviews/spockframework/spock/900 and needed to make some comments ;)

I asked on the [groovy-dev list](http://groovy-lang.org/mailing-lists.html) regarding the `initializationError`.

**Comment by MartyIX** [comment]
The build probably fails because of any of the recent Groovy bugfixes: https://issues.apache.org/jira/projects/GROOVY/issues/GROOVY-8497?filter=resolvedrecently I try to get more information.

**Comment by MartyIX** [comment]
https://github.com/apache/groovy/commit/fb125e42cf188ac98dc05d0b2188a72bad107ec3 - with this patch, the build passes for JDK 11 & Groovy 2.5.3-SNAPSHOT on my computer.

**Comment by MartyIX** [comment]
@leonard84 Well, nothing is set to stone. The problem is that Travis has some problems with downloading dependencies so it does not build as expected. My first goal is to make Travis green. However, we will have to wait for Groovy 2.5.3 final. When it is released, I'll try both variants - with removing final and without it. A qualified decision can then be made, what solution should be picked.

I'm kind of happy, that I can at least build Spock locally with JDK 11. :)

**Comment by adamkrol93** [comment]
Groovy 2.5.3 is relesed.

**Comment by MartyIX** [comment]
@adamkrol93 Yes, you can see that this commit uses 2.5.3. The thing is that I'm unable to get rid of the following exception:

```
        Caused by:
        java.lang.IllegalAccessError: Update to static final field org.spockframework.smoke.DefaultValuesOfUnsharedFields.$const$0 attempted from a different method (__$swapInit) than the initializer method <clinit> 
            at org.spockframework.smoke.DefaultValuesOfUnsharedFields.__$swapInit(SpecFields.groovy)
            at org.spockframework.smoke.DefaultValuesOfUnsharedFields.<clinit>(SpecFields.groovy)
```

The passes for me in Intellij IDEA but not in Gradle. I have tried Gradle 5.0 beta, to update various Spock dependencies, to comment out some code in SpecRewriter etc. to no avail.

Any clue is appreciated.

**Comment by szpak** [comment]
@MartyIX Have you asked about that on the Groovy mailing list?

**Comment by MartyIX** [comment]
@szpak I don't believe it will help. I think this is an issue in Spock as it changes some final values.

**Comment by leonard84** [comment]
Shouldn't removing the final modifier work? Have you checked the generated code? (via `gradlew coreConsole`)

**Comment by leonard84** [comment]
@MartyIX you need to open the AST via Script > `Inspect AST (Alt+T)`, Spocks changes are applied in the `Semantic Analysis` phase.

**Comment by leonard84** [comment]
@paulk-asert could you take another look at https://travis-ci.org/spockframework/spock/jobs/441363040

e.g.
``` 
java.lang.IllegalAccessError: Update to static final field spock.util.concurrent.PollingConditionsSpec.$const$0 attempted from a different method (__$swapInit) than the initializer method <clinit> 
            at spock.util.concurrent.PollingConditionsSpec.__$swapInit(PollingConditionsSpec.groovy)
            at spock.util.concurrent.PollingConditionsSpec.<clinit>(PollingConditionsSpec.groovy)
```

Spock moves its initialization to `$spock_initializeFields` and not `__$swapInit` furthermore I don't know where this `$const$0` comes from.

**Comment by marceloverdijk** [comment]
What is the status of this and what is needed?
I've reverted back to spock 1.1-groovy-2.4 for now but it's clearly not what we want. I guess more people will be starting to move to Java 11 soon...

**Comment by MartyIX** [comment]
@marceloverdijk It's necessary to figure out what causes the exceptions in tests (see https://travis-ci.org/spockframework/spock/jobs/447664830)

It's necessary to pinpoint where the bug comes from. Is it in Spock part, is it in Groovy? https://github.com/spockframework/spock/issues/911 hints where the problem might be, but not to me.

**Comment by jurna** [comment]
I've just got this issue (Update to static final field) with Java 10 and 1.2-groovy-2.5 (groovy 2.5.3)

**Comment by vanta** [comment]
Any update on this PR?

**Comment by leonard84** [comment]
Unfortunately no, it is still under investigation.

**Comment by paulk-asert** [comment]
Can you try the latest snapshot for 2.5.4? I believe this should be fixed.

**Comment by MartyIX** [comment]
I have pushed changes for 2.5.4 snapshot. It seems it does not fix the issue.

**Comment by leonard84** [comment]
@MartyIX there seems to be something wrong with your latest commit, travis is complaining `GitHub payload is missing a merge commit (mergeable_state: "unknown", merged: false)`

**Comment by leonard84** [comment]
@MartyIX the fix in 2.5.4 seems to have worked, the remaining errors are caused by Hibernate.

**Comment by MartyIX** [comment]
@leonard84 Yes, it can be fixed using newer version. 

Openjdk10 in Travis cannot download a dependency though: https://travis-ci.org/spockframework/spock/builds/452409018 ... Any idea how to make Travis download it? (It seems there's some cache)

**Comment by leonard84** [comment]
Seems to be some SSL issue in travis/jdk
> Could not GET 'https://plugins.gradle.org/m2/org/springframework/data/spring-data-releasetrain/Kay-SR11/spring-data-releasetrain-Kay-SR11.pom'.
> sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by MartyIX** [comment]
Unfortunately `oraclejdk10` is not supported on Travis CI (https://docs.travis-ci.com/user/languages/java/#using-java-10-and-later)

**Comment by szpak** [comment]
@MartyIX I just committed a workaround to "fix" build on Travis with OpenJDK 10. See https://github.com/sormuras/bach/pull/12 for more background.

**Comment by MartyIX** [comment]
@szpak Thank you. All green. Yeey :+1:

**Comment by szpak** [comment]
@paulk-asert Your change fixed the Spock build with Java 11. Thanks!

That issue could also impact other Groovy project trying to be Java 11 compatible. How many other things you have in your backlog before 2.5.4 could be released?

**Comment by MartyIX** [comment]
@leonard84 I believe this PR can be merged. Or do you have any objections?

**Comment by leonard84** [comment]
I'm currently on Devoxx, I'll take a look when I've time.

**Comment by henrik242** [comment]
(Maybe remove [WIP] from PR title)

**Comment by leonard84** [comment]
Thanks @MartyIX

**Comment by jtstorck** [comment]
This issue occurs with Groovy 2.5.7 (with spock-core:1.2-groovy-2.5):

`java.lang.IllegalAccessError: Update to non-static final field` _<class.field>_ `attempted from a different method ($spock_initializeFields) than the initializer method <init>`

The test passes when Groovy 2.5.4 is used.

**Pull request merged**
