### PR TITLE
Update docs to include info/examples for Spying instatiated objects

### PR DESCRIPTION
**Pull request by twicksell**

### CODE REVIEW

**Comment by szpak** [comment]
The failure looks strange as it should be caused by your changes...

**Comment by twicksell** [comment]
Yep, thats my fault. I didn't expect a docs change to fail a build, but I see whats happening. I'll fix and re-push.

**Comment by szpak** [comment]
Wow, I didn't know about that feature in Spock build mechanism :)

**Comment by twicksell** [comment]
Neither did I :) 
Good feature. I've updated my example so that its functional.

**Pull request merged**
