### PR TITLE
Fix handling of "is" as getter for boolean properties on Mocks

### LINKED ISSUE #1256: Mock Groovy Object expecteding "get" rather than "is" with dot notation accessor
# Issue description

In our testing of a groovy / grails application we have an object under test, into which we inject a Mock of an object, to mock out a method that is called.  In our migration to spock 2 (org.spockframework:spock-core:2.0-M4-groovy-3.0) we have hit an issue when the mock object has a method that returns a boolean - the method cannot be found when accessed by groovy's dot notation accessor.

When the dot notation is used for a boolean it looks for a method with "get" as the method prefix rather than "is". I have recreated this in a standalone groovy script (which I will link to).  So the Mock is an mock of a real object, which the class is:

```groovy
class ExampleData {

    boolean isCurrent() {
        true
    }
}
```

When this ExampleData is created as a Mock, its then called in the controller as follows:

```groovy
    def show1() {
       data.current ? "Data is current" : "Data is not current"
    }
```

When this is called - we get the following error:

```
JUnit5 launcher: passed=1, failed=1, skipped=0, time=502ms

Failures (1):
  Spock:TestV3:Test Mock Object Boolean accessor via dot-notation
    MethodSource [className = 'TestV3', methodName = 'Test Mock Object Boolean accessor via dot-notation', methodParameterTypes = '']
    => groovy.lang.MissingMethodException: No signature of method: ExampleData.getCurrent() is applicable for argument types: () values: []
Possible solutions: isCurrent()
       ExampleController.show1(testV3.groovy:61)
       TestV3.Test Mock Object Boolean accessor via dot-notation(testV3.groovy:23)
Caught: groovy.lang.GroovyRuntimeException
groovy.lang.GroovyRuntimeException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Caused by: groovy.lang.MissingMethodException: No signature of method: ExampleData.getCurrent() is applicable for argument types: () values: []
Possible solutions: isCurrent()
	at ExampleController.show1(testV3.groovy:61)
	at TestV3.Test Mock Object Boolean accessor via dot-notation(testV3.groovy:23)
```

So you can see when accessed via dot notation then you can see that its looking for `getCurrent()` rather than `isCurrent()`

# How to reproduce

So this can be reproduced with the following groovy code:

```groovy
@Grab('cglib:cglib-nodep:3.3.0')
@Grab('org.spockframework:spock-core:2.0-M4-groovy-3.0')
@GrabExclude('org.codehaus.groovy:*')
import spock.lang.Shared
import spock.lang.Specification


class TestV3 extends Specification {

    @Shared 
    ExampleData mockData

    def setup() {
        mockData = Mock(ExampleData) 
    }

    def "Test Mock Object Boolean accessor via dot-notation" () {

        given: "Test Controller"
        ExampleController controller = new ExampleController(data: mockData)

        when: "call test method"
        def result = controller.show1()

        then: "should call mock data"
        1 * mockData.isCurrent() >> true

        and: "should equal"
        result == "Data is current"
    }

    def "Test Mock Object Boolean accessor via method" () {

        given: "Test Controller"
        ExampleController controller = new ExampleController(data: mockData)

        when: "call test method"
        def result = controller.show2()

        then: "should call mock data"
        1 * mockData.isCurrent() >> true

        and: "should equal"
        result == "Data is current"
    }
}

class ExampleData {

    boolean isCurrent() {
        true
    }
}


class ExampleController {

    ExampleData data

    def show1() {
       data.current ? "Data is current" : "Data is not current" 
    }

    def show2() {
       data.isCurrent() ? "Data is current" : "Data is not current" 
    }

}

```

To run:

```
groovy testV3
```

You will see the error as per the description.

I can show that this works with previous version of spock by changing the dependency:

```
 diff testV2.groovy testV3.groovy
2c2
< @Grab('org.spockframework:spock-core:1.3-groovy-2.5')
---
> @Grab('org.spockframework:spock-core:2.0-M4-groovy-3.0')
8c8
< class TestV2 extends Specification {
---
> class TestV3 extends Specification {
```

and running with groovy v2.  This works

# Additional Environment information

## Java/JDK

```
openjdk version "11.0.8" 2020-07-14 LTS
OpenJDK Runtime Environment Zulu11.41+23-CA (build 11.0.8+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.41+23-CA (build 11.0.8+10-LTS, mixed mode)
```

## Groovy version

```
Groovy Version: 3.0.4 JVM: 11.0.8 Vendor: Azul Systems, Inc. OS: Mac OS X
```

## Build tool version

Grapes

## Operating System

Mac OS X 10.15.5

### Groovy Grape

```groovy
@Grab('cglib:cglib-nodep:3.3.0')
@Grab('org.spockframework:spock-core:2.0-M4-groovy-3.0')
@GrabExclude('org.codehaus.groovy:*')
```

### PR DESCRIPTION
**Pull request by leonard84**
fixes #1256

### CODE REVIEW

**Comment by kriegaex** [comment]
Looks good to me. Locally I also added tests for another example class which actually uses a `getCurrent()` instead of `isCurrent()` in order to verify that non-standard getters for boolean properties are still working. I also tested that the change in getter handling does not affect setters by adding and testing `setCurrent(boolean current)` for both cases. You might think this is somewhat over-specified, but if you are interested I can post the additional code here. Either way, the tests passed as expected.

**Comment by leonard84** [comment]
@kriegaex thanks for testing it out, I've added a test for the get-style boolean accessor, however I don't think, that an setter test is necessary since it doesn't have any special cases and is already covered by existing tests.

**Comment by kriegaex** [comment]
Yes, I know because I have extended your new test. Maybe I was imprecise in my explanation, sorry. Yes, maybe the spec is fine without testing setters, but I also tested the following two cases not covered by your test:
  * Common special case: getter is named `boolean getCurrent()` ***instead of*** `boolean isCurrent()` → test passes
  * Rare edge case: class has two getters `boolean getCurrent()` ***in addition to*** `boolean isCurrent()` → test fails if we assume that according to Java Beans conventions the `boolean isCurrent()` should have preference and `boolean getCurrent()` should be the fall-back. You implemented it the other way around and I would suggest to change it.
  * We could also check the correct behaviour for non-boolean getters named `isSomething()`. They should always be ignored, even if not `getSomething()` is found. I have not implemented that yet. Even if that one would pass now, I think we should add it to the test harness because it would help to detect regression errors in case of future refactorings.

Would you like to address the cases I mentioned? I could show you the code or suggest it as a PR on your own PR (funny!) in your private fork.

**Comment by kriegaex** [comment]
Thanks for the update. The 3rd case is still not addressed. I mean this:

```java
class ExampleData {
  // (...)

  boolean isActive() {
    false
  }

  boolean getActive() {
    false
  }

  String isName() {
    ""
  }

  String getName() {
    ""
  }
}
```

And then:

```java
  @Issue("https://github.com/spockframework/spock/issues/1256")
  def "Mock object boolean (get + is) accessor via dot-notation" () {
    given:
    ExampleData mockData = Mock(ExampleData)

    when: "query via property syntax"
    def result = mockData.active ? "Data is current" : "Data is not current"

    then: "calls mock, preferring 'is' to 'get' for boolean getters"
    1 * mockData.isActive() >> true
    0 * mockData.getActive()

    and:
    result == "Data is current"
  }

  @Issue("https://github.com/spockframework/spock/issues/1256")
  def "Mock object non-boolean (get + is) accessor via dot-notation" () {
    given:
    ExampleData mockData = Mock(ExampleData)

    when: "query via property syntax"
    def result = mockData.name ? "Data is current" : "Data is not current"

    then: "calls mock, preferring 'get' to 'is' for non-boolean getters"
    1 * mockData.getName() >> "Gettysburg"
    0 * mockData.isName()

    and:
    result == "Data is current"
  }
```

The non-boolean feature passes, the boolean one fails.

**Comment by kriegaex** [comment]
Oops, my assumption that for `boolean` properties `isX()` would take preference if it exists alongside `getX()` seems to have been wrong. I just noticed that standard Groovy seems to always prefer `getX()` if it exists, no matter if the return type is `boolean` or not. In that case I am suggesting this:

```java
  boolean isActive() {
    false
  }

  boolean getActive() {
    false
  }

  String isName() {
    null
  }

  String getName() {
    null
  }

  String isDummy() {
    null
  }
```

```java
  @Issue("https://github.com/spockframework/spock/issues/1256")
  def "Mock object boolean (get + is) accessor via dot-notation" () {
    given:
    ExampleData mockData = Mock(ExampleData)

    when: "query via property syntax"
    def result = mockData.active ? "Data is current" : "Data is not current"

    then: "calls mock, preferring 'is' to 'get' for boolean getters"
    1 * mockData.getActive() >> true
    0 * mockData.isActive()

    and:
    result == "Data is current"
  }

  @Issue("https://github.com/spockframework/spock/issues/1256")
  def "Mock object non-boolean (get + is) accessor via dot-notation" () {
    given:
    ExampleData mockData = Mock(ExampleData)

    when: "query via property syntax"
    def result = mockData.name ? "Data is current" : "Data is not current"

    then: "calls mock, preferring 'get' to 'is' for non-boolean getters"
    1 * mockData.getName() >> "X"
    0 * mockData.isName()

    and:
    result == "Data is current"
  }

  @Issue("https://github.com/spockframework/spock/issues/1256")
  def "Mock object non-boolean (is) pseudo accessor via dot-notation" () {
    given:
    ExampleData mockData = Mock(ExampleData)

    when: "query via property syntax"
    mockData.dummy

    then: "non-boolean 'is' getter is illegal"
    thrown MissingPropertyException
  }
```

They should pass already, but a strong regression test harness for classes under test containing comments about "unreliable hacks" might be helpful for future refactoring, like I said.

**Comment by kriegaex** [comment]
Couldn't resist to try and create a PR from my fork to yours, basically my PR on your PR branch. If you think my tests are over-specified, just reject them, but I created them in order to understand the situation better and didn't want to throw them away.

**Comment by leonard84** [comment]
While you are correct that in accordance with [JavaBeans Specification 1.01](https://download.oracle.com/otndocs/jcp/7224-javabeans-1.01-fr-spec-oth-JSpec/) the `is`-variant should have priority, groovy seems to prefer the `get`-variant, if both are present. (tested with groovy-2.5.14)

> In addition, for boolean properties, we allow a getter method to match the pattern: 
>   `public boolean is<PropertyName>();`
> This `“is<PropertyName>”` method may be provided instead of a `“get<PropertyName>”` method, or it may be provided in addition to a `“get<PropertyName>”` method.In either case, if the `“is<PropertyName>”` method is present for a boolean property then we will use the `“is<PropertyName>”` method to read the property value.

The [property naming convention](https://docs.groovy-lang.org/latest/html/documentation/#properties) of groovy doesn't say anything in regards to that.

So we could follow the JavaBean Spec, but this would actually break how groovy would access these properties. 

@paulk-asert could you comment on this, will this be "fixed" in groovy 4?

```
public class Sut {
    public boolean isExited() {
        return true;
    }

    public boolean getExited() {
        return false;
    }
}
```

```
class SutTest extends Specification {

    def "default groovy behavior"() {
        expect:
        new Sut().exited
    }
    def "default groovy behavior getter"() {
        expect:
        !new Sut().getExited()
    }
    def "default groovy behavior is-getter"() {
        expect:
        new Sut().isExited()
    }

    def "GSut default groovy behavior"() {
        expect:
        new GSut().exited
    }
    def "GSut default groovy behavior getter"() {
        expect:
        !new GSut().getExited()
    }
    def "GSut default groovy behavior is-getter"() {
        expect:
        new GSut().isExited()
    }
}

class GSut {
    boolean isExited() {
        return true;
    }

    boolean getExited() {
        return false;
    }
}
```

**Comment by paulk-asert** [comment]
I have lost track as to the reasons Groovy prefers the getter. I will need to dive into the git history and see if it reveals anything. But it is certainly very much an edge case and something we could look at for Groovy 4. Certainly, if you have a class with both variants but returning different values, you have a very unintuitive class.

**Comment by leonard84** [comment]
I agree that this an edge case, for now I would say that Spock should follow Groovys behavior and prefer the `get` variant.

**Comment by kriegaex** [comment]
> I agree that this an edge case, for now I would say that Spock should follow Groovys behavior and prefer the `get` variant.

I implicitly agreed already, because my additional tests cover the current Groovy behaviour.

If any future Groovy version would introduce a breaking change that would make Groovy more compliant to the Java Beans specification as quoted by @leonard84, we could asjust both tests and Spock code accordingly. Thanks @paulk-asert for your insightful comments.

_Slightly off topic: I did not imagine that me commenting on a small Spock PR, mostly thinking aloud and then adding a few test cases for my own understanding, would lead to such an interesting discussion, considering myself a merely a minor contributor in this process. OTOH, this is exactly what I see on an almost daily basis in the agile teams I coach during my daytime job. The collaborative part of software development can hardly be overrated. Thanks to everyone here for the chance to learn and grow alongside you._

**Review by Vampire — APPROVED** [review]
lgtm

**Pull request merged**
