### PR TITLE
Add Groovy 4 support

### PR DESCRIPTION
**Pull request by leonard84**

### CODE REVIEW

**Comment by szpak** [comment]
I merged in my initial changes with fixing stack trace related assertions broken by Indy calls (enabled by default in Groovy 4, but still possible with Groovy 2.5 and 3).

What's interesting, there all the tests are executed from Idea, two still fails with:
```
Condition not satisfied:

methodName == "-" || methodName == traceElem.methodName
|          |      |  |          |  |         |
|          |      |  |          |  |         foo_closure3
|          |      |  |          |  apackage.ASpec.foo_closure3(Script_3fd3a5801e374ef551955ab837465535.groovy:7)
|          |      |  |          false
|          |      |  |          1 difference (91% similarity)
|          |      |  |          foo_closure(1)
|          |      |  |          foo_closure(3)
|          |      |  foo_closure1
|          |      false
|          false
|          12 differences (0% similarity)
|          (foo_closure1)
|          (------------)
foo_closure1


	at org.spockframework.EmbeddedSpecification.stackTraceLooksLike_closure3(EmbeddedSpecification.groovy:58)
	at groovy.lang.Closure.call(Closure.java:419)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
	at org.spockframework.EmbeddedSpecification.stackTraceLooksLike(EmbeddedSpecification.groovy:51)
	at org.spockframework.smoke.StackTraceFiltering.when creation of data provider fails, stack trace points to corresponding parameterization(StackTraceFiltering.groovy:229)
```

as for some reasons, there seems to be more closures in a generated script file (and own is no. 3). It doesn't happen when StackTraceFiltering tests are executed separately. I leave it for further investigation.

**Comment by msgilligan** [comment]
> I don't intend to release a 4.0 variant for 2.1 unless groovy 4.0 final is already release, but I don't want to wait that long.

The Groovy devs are voting on Groovy 4.0 final release as of today.

**Comment by szpak** [comment]
All CI build are green after I disabled `@CompileStatic` transformation in a few tests and test configuration classes.

However, I don't know why it fails that way and what's more strange, why some of those places fails also with JDK 8 and 11 (not just 17). Could we have some problem with build-cache on CI?
Another interesting thing is that I'm not able to reproduce (some) of those problems locally. Only the one place in the first "workaround" commit fails on my machine (with different JDKs). Those in Spring test configuration work fine (even with `gw clean check -Dvariant=4.0 --no-build-cache`).

I've just asked on the Groovy Slack about their ideas:
https://groovy-community.slack.com/archives/C2NEFCM55/p1643236824027100

In addition, I wonder, which Groovy 4 specific features (such as (emulated) sealed classes) you think are worth testing explicitly with Spock?

**Comment by szpak** [comment]
Btw, some tests are not stable on CI.

One parallel test [failed](https://github.com/spockframework/spock/runs/4958772266?check_suite_focus=true#step:8:130) twice with JDK 8 and Groovy 3.0 and 4.0. However, it doesn't seem to be related:

```
ParallelSpec > @ResourceLock with only READ allows parallel execution of data-driven features FAILED
    Condition not satisfied:

    atomicInteger.get() == 3
    |             |     |
    3             1     false
        at apackage.ASpec.writeA(Script_9186d4f70d72d15ebba0478d4c746046.groovy:14)
```


Another [one](https://github.com/spockframework/spock/runs/4958926891?check_suite_focus=true#step:8:130) (in a separate run):

```
TimeoutExtension > stack trace shows where thread is hung FAILED
    org.gradle.internal.exceptions.DefaultMultiCauseException: Multiple Failures (4 failures)
    	org.spockframework.runtime.SpockComparisonFailure: Condition not satisfied:

    trace.size() == lines.size()
    |     |      |  |     |
    |     1      |  |     2
    |            |  [apackage.ASpec|helper|7,       apackage.ASpec|foo|3]
    |            false
    [apackage.ASpec.foo(Script_4c375ed6a7d6b75b709b5b6f940f6e5c.groovy:3)]

    	org.spockframework.runtime.SpockComparisonFailure: Condition not satisfied:

    trace.size() == lines.size()
    |     |      |  |     |
    |     1      |  |     2
    |            |  [apackage.ASpec|helper|7,       apackage.ASpec|foo|3]
    |            false
    [apackage.ASpec.foo(Script_4c375ed6a7d6b75b709b5b6f940f6e5c.groovy:3)]

    	org.spockframework.runtime.WrongExceptionThrownError: Expected exception of type 'org.spockframework.runtime.SpockTimeoutError', but no exception was thrown
    	org.spockframework.runtime.WrongExceptionThrownError: Expected exception of type 'org.spockframework.runtime.SpockTimeoutError', but no exception was thrown
        at org.spockframework.runtime.ErrorInfoCollector.assertEmpty(ErrorInfoCollector.java:32)
        at org.spockframework.runtime.IterationNode.execute(IterationNode.java:49)
```

**Comment by lptr** [comment]
Given that Spock 2.1 is not released yet, and that Groovy 4 is released now, is this going to make it into Spock 2.1?

**Comment by szpak** [comment]
> Given that Spock 2.1 is not released yet, and that Groovy 4 is released now, is this going to make it into Spock 2.1?

Groovy 4 GA is out, so assuming no other obstacles, it will be a part of 2.1.

**Comment by szpak** [comment]
> Can the reference to Groovy 4 RC2 be updated?

I've just updated it. Thanks for your reminder.

**Pull request merged**
