### PR TITLE
Fix NullPointerException happening after exception in data provider

### PR DESCRIPTION
**Pull request by Vampire**

### CODE REVIEW

**Comment by leonard84** [comment]
Is this a general problem?
- Yes: Why is it dependent on the changes
- No: Why isn't it part of the other PR if it introduced the problem and isn't merged yet.

**Comment by Vampire** [comment]
> Is this a general problem?

Yes

> Yes: Why is it dependent on the changes

It is not really, I hit it while doing the `filter:` implementation.
The `filter:` implementation is also not strictly dependent on the `combined:` changes,
but I thought mainly for the examples in the documentation combining `filter:` with `combined:` is a good idea.

If you want to quickly get this through for the M3 tomorrow, I can of course rebase it onto `master`.

**Comment by Vampire** [comment]
Rebased

**Comment by Vampire** [comment]
The main point actually is, that the `filter:` code cannot work without this bug fixed, that's why I had it in that stack.
Now it does not build right now unless this is merged and the other two rebased.
But I guess this gets in pretty fast now that you are active currently. :-)

**Comment by Vampire** [comment]
* **#1925** <a href="https://app.graphite.dev/github/pr/spockframework/spock/1925?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Vampire and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by leonard84 — APPROVED** [review]

**Pull request merged**
