### PR TITLE
RetryExtension

### PR DESCRIPTION
**Pull request by Fuud**
This PR based on #561.

New `@Retry` annotation was introduced. If test failed it will be rerun up to `Retry.value` times. Retry count can be configured also via system property. Use `Retry.systemProperty` to specify system property name.

```
      @Shared int runCount = 0;

      @Retry(5)
      def test(){
        runCount++;
        expect:
          runCount == 1 + 5
      }
```

### CODE REVIEW

**Comment by Fuud** [comment]
@anotherchrisberry Please review.

**Comment by szpak** [comment]
Minor comments issues, but In general the retry part looks good to me.

**Comment by anotherchrisberry** [comment]
Seems reasonable to me - I would be very happy to see this as part of the framework so I could retire my extension!

**Comment by Aloren** [comment]
I am very interested in current PR. Will it be merged? And when? Thanks.

**Comment by leonard84** [comment]
A different solution was implemented with #755

**Pull request closed without merging**
