### PR TITLE
Add annotations to enable static compilation within a Specification.w…

### PR DESCRIPTION
**Pull request by RobeEW**
…ith closure

### CODE REVIEW

**Comment by szpak** [comment]
`@DeletesTo` has been introduced in Groovy 2.1 while Spock is still compatible with Groovy 2.0

**Comment by szpak** [comment]
Could you provide an example (as a test) presenting how it could be used?

If Groovy 2.1were able to improve static compilation in Spock in general maybe it would be a good point to remove support for it in the newer versions.

**Comment by leonard84** [comment]
`@CompileStatic` on specs won't work in many cases and provides not a good dev experience. IMHO it should be used with `main` code and maybe some test utilities but not for specs.

**Comment by RobeEW** [comment]
The primary purpose of this change is not to permit use of `@CompileStatic` but to allow IDEs such as IntelliJ to hyperlink to properties within a `with(parent) {}` (and not display them as dynamically resolved) even if using dynamic compilation.

(Personally I think whether people do or do not use `@CompileStatic` on their specs should be purely personal/team preference, and enabling more cases in which people can do so if they wish is therefore A Good Thing™ regardless...)

**Comment by leonard84** [comment]
Yes better IDE support is always welcome, unfortunately this PR requires Groovy 2.1 as @szpak already pointed out, so we will have to wait for a future version of spock before we can merge it.

**Pull request closed without merging**
