### PR TITLE
Upgrade Gradle wrapper to version 8.1

### PR DESCRIPTION
**Pull request by bmscomp**
Upgrade Gradle wrapper to version 8.1 and update value of `distributionSha256Sum` in `gradle-wrapper.properties` file 
Remove obsolet gradlew.bat file  (not compatible with recents version of Gradle)

### CODE REVIEW

**Comment by Vampire** [comment]
What do you mean with `gradlew.bat` no longer being compatible?

**Comment by bmscomp** [comment]
Heoo @Vampire  yes it's not more provided by the recent versions of Gradle, the new gradlew contains both versions of executable for windows and linux like systems

**Comment by bmscomp** [comment]
@Vampire  please let me check more, I'll get back with more details or I will update my pull request :)

**Comment by Vampire** [comment]
Maybe you was confused by the fact that the file did not change after the `wrapper` call, but that only means that the same file was generated without changes. `gradlew` can on Windows still only be used from some `sh` derivative like Cygwin, WSL, or Git Bash from Git for Windows. In cmd or powershell you still need the Batch file.

**Comment by bmscomp** [comment]
I updated the pull request to keep the .bat file, I agree I forget the powershell and cmd , thanks so much for the remember @Vampire

**Review by leonard84 — APPROVED** [review]

**Review by Vampire — APPROVED** [review]

**Pull request merged**
