### PR TITLE
Do not convert implicit "this" expression like when calling the constructor of a non-static inner class

### PR DESCRIPTION
**Pull request by Vampire**
This change is [Reviewable](https://reviewable.io/reviews/spockframework/spock/930)

### CODE REVIEW

**Comment by Vampire** [comment]
I don't really understand the codecov complain. I added one ternary expression and I added a test for the new case, what is it complaining about? :-/

**Comment by Vampire** [comment]
Ah, now I understand it.
It is the same reason I had difficulty debugging this.
It is because if is not executed during test runtime, but during test compilation.
And thus codecov does not see the coverage.
Is it ok that codecov is complaining then?

**Comment by leonard84** [comment]
You can write an EmbeddedSpec, this should exercise the code during test runtime.

**Comment by Vampire** [comment]
Ah, right, forgot about that.
That would have also made the debugging much easier.
I debugged the gradle process to debug my changes. :-D
Thanks for reminding me.

**Comment by leonard84** [comment]
I get that this fixes a bug. What I'm uncertain about is, whether there is any real use-case for having a non-`static` inner-class, or is it just having to forgotten the `static` keyword? So is there a use-case or  should we just disallow non-`static` inner-classes or just add the `static` modifier?

**Comment by Vampire** [comment]
Well, I hit the error when I fixed the others so fixed this one too.
I'm not sure what it was, maybe the try to get a nice test for the same class from different class loaders case or so.
But it was probably not a real use-case.

I'm not sure whether there are valid use-cases for non-static inner classes.
But maybe there are other cases where this hits?
I don't have the internals of the compiler in head enough to know where implicit `this` references are inserted besides the constructors of non-static inner classes.

If this is really the only case, it might also be a solution to forbid them or make them `static` automatically, yes. While the latter will result in not really expected behavior if you actually access state of the specification in the class and it is automatically made static and you get compilation errors because accessing instance state from static context.

**Pull request merged**
