### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**
This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).

The misspellings have been reported at https://github.com/jsoref/spock/commit/a935d5228b1b516df7bff8f68068f47f63ebc4a7#commitcomment-45533998

The action reports that the changes in this PR would make it happy: https://github.com/jsoref/spock/commit/140fa3a149e15459722bb811060fa78acce4fd54

Note: this PR does not include the action. If you're interested in running a spell check on every PR and push, that can be offered separately.

---
I'm assuming that there will be some iteration, and that it's unlikely that my commit messages would be accepted even if the first letter of them were capitalized.

It's quite possible that some of these changes are to APIs and can't be accepted, just let me know, dropping commits is trivial.

### CODE REVIEW

**Review by kriegaex — APPROVED** [review]
Looking good to me. There is one renamed method, which means a breaking change, but I think it should be correctly named anyway.

**Review by leonard84 — APPROVED** [review]

**Comment by leonard84** [comment]
Thanks, @jsoref we might take a look at adding that actions once it has been properly released and doesn't require the users to run perl locally. Isn't it possible to add review comments with `suggestions` that could simply be applied directly?

**Comment by jsoref** [comment]
@leonard84: the perl was designed as a convenience (at some point I'm hoping to let you talk to the tool and have it create a commit that does what it suggests).

Today you can just copy the bulleted items into the `expect` file -- as long as each gets its own line in the file, the tool will be happy. 

You could add a `advice.txt` file explaining how to copy the output into the file instead. Note that doing this won't prune obsolete items (which means if you temporarily had a typo and actively remove the typo, someone later can reintroduce the typo w/o the tool warning).

**Comment by jsoref** [comment]
@leonard84: yeah I'm working on those bits.

**Pull request merged**
